spring:
  application:
    name: bankaccount
  datasource:
    url: jdbc:postgresql://localhost:5332/postgres
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5332/postgres
    user: postgres
    password: password
    locations: classpath:db/migration
    baselineOnMigrate: true