spring:
  application:
    name: bankaccount
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true