CREATE TABLE account (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount numeric NOT NULL default 0.0,
    closed boolean NOT NULL default false
);

insert into account (amount, closed) values (100.5, false);
insert into account (amount, closed) values (-10.2, false);
insert into account (amount, closed) values (200.5, false);
insert into account (amount, closed) values (-1000, false);
insert into account (amount, closed) values (100.5, false);
insert into account (amount, closed) values (-1230, true);
insert into account (amount, closed) values (100.5, false);
insert into account (amount, closed) values (-10.2, true);